dist: trusty
language: node_js
node_js:
  - 13
  - 12
  - 11
cache:
  directories:
    - node_modules
install:
  - npm ci
before_script:
  - npm outdate
  - npm audit
script:
  - npm run test:browser:ci
before_deploy:
  - npm run build
deploy:
  - provider: npm
    email: novikovio74@gmail.com
    skip_cleanup: true
    tag: latest
    on:
      branch: master
      repo: Hooked74/highlight
    api_key:
      secure: nRTgflTxKINhoGbs4AOEIW7GnLgd3+IR++Xc9LxAujoB3gI/3I4radNYA4uiwJDEy2pYZJI82HNLXiOYXz225ENyTaCBx9zbx7Y7dlPAulK95rdjTQBt6oeJE9PoCF7TpTxqFjHC3fipGJf0OzBDIeLTNlXawt53g8+sFdwSJ/ea1Um3qGnw4BK2py8UxQ5zgmhbjrT0yFMcgFYKvFzuewdgP9NukuZfRngp0icy7nnf4dJn8MqPFnO938h58QHO+CsjPgERDsCBSkSoLiJZR+le9JtCsZddux3zXiyxlOBpYZIR4RIrJQ2S5kiVOKrsZvEXFQ3opxpPA4FQA8LUxhJlBr8skkTtT/b2+OVXYYWZIHhwN8ZQ2MYJ6vcCwLXfQcJvVw+HIb3Qx1BXp8QtVXOT7QYyBqiPozeEMru2C8AlZ3Z17UWFQiA5fwOZy/4ODCXihaa6yrEycl7qqjUAU1Ys/v1Iv+hzlUc8H74H8m/TuO1uxNr8Zz2a95hSEdFCk+3z6xty/vD2ycpqHs11LBaf6WF84t7OLVIGqTg1VLJoaOs1I/uddxvJ5BI7VkGAY6TgZLKAWkiTI/M9OkHUXG1pEtHFz6Don4fUZXU7mNRIXlMD8YA8DMamLfebzXePL0F//F7KJhPfQ9zZffmJmznJs0EDZjqwlSrs1hPSmHk=
